import { HeroRating, Tier } from './hero';

export const offense: HeroRating[] = [
    { heroId: 'wv', tier: Tier.DemiGod, tags: {awake: 1 }},
    { heroId: 'aa', tier: Tier.DemiGod, tags: { awake: 1}},
    { heroId: 'ice', tier: Tier.God },
    { heroId: 'wv(x23)', tier: Tier.DemiGod },
    { heroId: 'rogue', tier: Tier.DemiGod },
    { heroId: 'storm', tier: Tier.Amazing, tags: { awake: 1 }},
    { heroId: 'pl', tier: Tier.Amazing, tags: { awake: 1 }},
    { heroId: 'cable', tier: Tier.DemiGod },
    { heroId: 'nc', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'cc', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'beast', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'gb', tier: Tier.Amazing },
    { heroId: 'dp(xf)', tier: Tier.Meh, tags: { awake: 1 } },
    { heroId: 'magneto', tier: Tier.Good },
    { heroId: 'oml', tier: Tier.Good },
    { heroId: 'col', tier: Tier.Meh },

    { heroId: 'dv', tier: Tier.DemiGod, tags: { awake: 1 } },
    { heroId: 'sw', tier: Tier.Amazing, tags: { awake: 1, highSig: 1 } },
    { heroId: 'gr', tier: Tier.God },
    { heroId: 'magik', tier: Tier.God },
    { heroId: 'glt', tier: Tier.DemiGod },
    { heroId: 'dm', tier: Tier.DemiGod },
    { heroId: 'th', tier: Tier.DemiGod },
    { heroId: 'ms', tier: Tier.DemiGod },
    { heroId: 'mp', tier: Tier.DemiGod },
    { heroId: 't(jf)', tier: Tier.Good, tags: {awake: 1 } },
    { heroId: 'if', tier: Tier.Good, tags: {awake: 1 }  },
    { heroId: 'mordo', tier: Tier.Amazing  },
    { heroId: 'ds', tier: Tier.Amazing },
    { heroId: 'uc', tier: Tier.Meh, tags: {awake: 1 }  },
    { heroId: 'jug', tier: Tier.Good },
    { heroId: 'loki', tier: Tier.Meh },

    { heroId: 'gp', tier: Tier.God },
    { heroId: 'blade', tier: Tier.God },
    { heroId: 'cb', tier: Tier.DemiGod },
    { heroId: 'bw', tier: Tier.Good, tags: {awake: 1, highSig: 1 } },
    { heroId: 'el', tier: Tier.DemiGod },
    { heroId: 'dd(c)', tier: Tier.Good, tags: {awake: 1, highSig: 1 } },
    { heroId: 't(r)', tier: Tier.Good, tags: {awake: 1, highSig: 1 } },
    { heroId: 'he', tier: Tier.DemiGod },
    { heroId: 'p', tier: Tier.Amazing },
    { heroId: 'ws', tier: Tier.Amazing },
    { heroId: 'kn', tier: Tier.Amazing },
    { heroId: 'av', tier: Tier.Amazing },
    { heroId: 'bp(c)', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'mk', tier: Tier.Amazing },
    { heroId: 'kp', tier: Tier.Amazing },
    { heroId: 'falcon', tier: Tier.Good },
    { heroId: 'dd (n)', tier: Tier.Good },
    { heroId: 'bp(cw)', tier: Tier.Meh },

    { heroId: 'med', tier: Tier.Amazing, tags: { awake: 1 }, synergy: { bb: 1} },
    { heroId: 'hp', tier: Tier.God },
    { heroId: 'ang', tier: Tier.DemiGod },
    { heroId: 'thor', tier: Tier.Amazing, tags: { awake: 1} },
    { heroId: 'drax', tier: Tier.DemiGod },
    { heroId: 'mm', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'cm', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'bb', tier: Tier.Amazing },
    { heroId: 'phoenix', tier: Tier.Amazing },
    { heroId: 'sms', tier: Tier.Amazing },
    { heroId: 'gamora', tier: Tier.Amazing },
    { heroId: 'kg', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'venom', tier: Tier.Meh, tags: { awake: 1 } },
    { heroId: 'sim', tier: Tier.Meh, tags: { awake: 1 } },
    { heroId: 'vp', tier: Tier.Good },
    { heroId: 'ronan', tier: Tier.Good },
    { heroId: 'carnage', tier: Tier.Meh, tags: { awake: 1 } },
    { heroId: 'groot', tier: Tier.Meh },
    { heroId: 'kk', tier: Tier.Meh },

    { heroId: 'sl', tier: Tier.DemiGod, tags: { awake: 1 } },
    { heroId: 'sm(ts)', tier: Tier.God },
    { heroId: 'vison', tier: Tier.Amazing, tags: { awake: 1} },
    { heroId: 'ultron', tier: Tier.DemiGod },
    { heroId: 'do', tier: Tier.DemiGod },
    { heroId: 'nebula', tier: Tier.Amazing },
    { heroId: 'p(2099)', tier: Tier.Amazing },
    { heroId: 'gg', tier: Tier.Amazing },
    { heroId: 'rr', tier: Tier.Amazing },
    { heroId: 'yondu', tier: Tier.Amazing },
    { heroId: 'htd', tier: Tier.Good },
    { heroId: 'kang', tier: Tier.Good },
    { heroId: 'vulture', tier: Tier.Good },
    { heroId: 'im', tier: Tier.Meh, tags: { awake: 1 } },
    { heroId: 'cw', tier: Tier.Good },
    { heroId: 'wm', tier: Tier.Meh },
    { heroId: 'hb', tier: Tier.Meh },
    { heroId: 'ip', tier: Tier.Meh },

    { heroId: 'hulk', tier: Tier.Amazing, tags: { awake: 1} },
    { heroId: 'yj', tier: Tier.DemiGod },
    { heroId: 'ca(ww2)', tier: Tier.DemiGod },
    { heroId: 'quake', tier: Tier.DemiGod },
    { heroId: 'ca(c)', tier: Tier.Amazing },
    { heroId: 'sm(c)', tier: Tier.Amazing },
    { heroId: 'electro', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'sg', tier: Tier.Good, tags: { awake: 1} },
    { heroId: 'sm(mm)', tier: Tier.Good },
    { heroId: 'rh', tier: Tier.Good },
    { heroId: 'rhino', tier: Tier.Good },
    { heroId: 'jf', tier: Tier.Meh },
    { heroId: 'sh', tier: Tier.Meh },
    { heroId: 'lc', tier: Tier.Meh },
    { heroId: 'ab', tier: Tier.Meh },
    { heroId: 'am', tier: Tier.Meh },
];

export const defense: HeroRating[] = [];
    